//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURANT
    {
        public int ID_COURANT { get; set; }
        public Nullable<int> ID_GENRE { get; set; }
        public string LIBELLE_COURANT { get; set; }
    
        public virtual GENRE GENRE { get; set; }
    }
}
