//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIVRE
    {
        public int ID_LIVRE { get; set; }
        public Nullable<decimal> ISBN { get; set; }
        public string TITRE { get; set; }
        public string INFO_EDITEUR { get; set; }
        public Nullable<System.DateTime> ANNEE_EDITION { get; set; }
        public Nullable<int> ID_AUTEUR { get; set; }
        public Nullable<int> ID_GENRE { get; set; }
        public string IMAGE_LIVRE { get; set; }
        public string URL_IMAGE_LIVRE { get; set; }
        public string URL_PDF { get; set; }
    
        public virtual AUTEUR AUTEUR { get; set; }
        public virtual GENRE GENRE { get; set; }
    }
}
