//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_BIBLIOTHEQUEEntities : DbContext
    {
        public BD_BIBLIOTHEQUEEntities()
            : base("name=BD_BIBLIOTHEQUEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTEUR> AUTEURS { get; set; }
        public virtual DbSet<COURANT> COURANTS { get; set; }
        public virtual DbSet<GENRE> GENRES { get; set; }
        public virtual DbSet<LIVRE> LIVRES { get; set; }
    }
}
